# Generated by Django 5.1.7 on 2025-03-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='creat_date',
            new_name='create_date',
        ),
    ]
