# Generated by Django 5.1.7 on 2025-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_writing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
