# Generated by Django 5.1.7 on 2025-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_writing_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dairy_images/'),
        ),
    ]
